// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_rjackso3.Models;

namespace Mission06_rjackso3.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230213200807_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mission06_rjackso3.Models.NewMovieData", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action",
                            Director = "Katsuhiro Otomo",
                            Edited = false,
                            Rating = "R",
                            Title = "Akira",
                            Year = (ushort)1988
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action",
                            Director = "Denis Villeneuve",
                            Edited = false,
                            Rating = "R",
                            Title = "Blade Runner 2049",
                            Year = (ushort)2017
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action",
                            Director = "Nicolas Winding Refn",
                            Edited = false,
                            Rating = "R",
                            Title = "Drive",
                            Year = (ushort)2011
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
